### ISSUE TITLE
new feature for Meme cmd

### ISSUE THREAD

**Issue by Necrozma200** [Dhravya/Spacebot#18]
remove the subreddits you liked from the code in utilities cog and let people add their favourite subreddits so the memes are more appropriate and as they like

**Comment by Dhravya** [comment]
That's a good idea, but the issue is that not everyone knows how to set up a bot for their server. The idea when adding meme subreddits myself was that the meme command will be ready, out of the box. Yes, one possible solution could be to add some "default" subreddits and then let them set their own 3 subreddits, which will then delete the default ones

**Comment by Necrozma200** [comment]
yeah maybe that's good too
